export const INDUSTRY_OPTIONS = [
    { label: "General", value: "General" },
    { label: "Finance & Banking", value: "Finance & Banking" },
    { label: "Investment Management", value: "Investment Management" },
    { label: "Insurance", value: "Insurance" },
    { label: "Accounting", value: "Accounting" },
    { label: "Agriculture", value: "Agriculture" },
    { label: "Media & Entertainment", value: "Media & Entertainment" },
    { label: "Healthcare", value: "Healthcare" },
    { label: "Transportation", value: "Transportation" },
    { label: "Manufacturing", value: "Manufacturing" },
    { label: "Construction", value: "Construction" },
    { label: "Consultant", value: "Consultant" },
    { label: "Technology", value: "Technology" },
    { label: "Government", value: "Government" },
    { label: "Marketing", value: "Marketing" },
    { label: "Other", value: "Other" },
  ];
  
  export const ROLE_OPTIONS = [
    { label: "Executive / C-Suite", value: "Executive / C-Suite" },
    { label: "Accountant", value: "Accountant" },
    { label: "Bookkeeper", value: "Bookkeeper" },
    { label: "Controller", value: "Controller" },
    { label: "Analyst", value: "Analyst" },
    { label: "Product Manager", value: "Product Manager" },
    { label: "Engineer / Developer", value: "Engineer / Developer" },
    { label: "Marketer", value: "Marketer" },
    { label: "Manufacturer", value: "Manufacturer" },
    { label: "CFO", value: "CFO" },
    { label: "Sales & RevOps", value: "Sales & RevOps" },
    { label: "Consultant", value: "Consultant" },
    { label: "Operations", value: "Operations" },
    { label: "Financial Advisor", value: "Financial Advisor" },
    { label: "Support", value: "Support" },
  ];